{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-alb
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /api/user/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.userService.name }}
                port:
                  number: 4000
          - path: /api/device
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.deviceService.name }}
                port:
                  number: 4000
          - path: /api/cart
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.cartService.name }}
                port:
                  number: 4000
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.orderService.name }}
                port:
                  number: 4000
{{- end }}