{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webapp.fullname" . }}-ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - eksdevops2.daohaithuan.click
      secretName: eksdevops2-tls
  rules:
    - host: eksdevops2.daohaithuan.click
      http:
        paths:
          - path: /api/user/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.userService.name }}
                port:
                  number: {{ .Values.services.userService.port }}
          - path: /api/device
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.deviceService.name }}
                port:
                  number: {{ .Values.services.deviceService.port }}
          - path: /api/cart
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.cartService.name }}
                port:
                  number: {{ .Values.services.cartService.port }}
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.orderService.name }}
                port:
                  number: {{ .Values.services.orderService.port }}
{{- end }}
